version: '3'
services:
  user-interface:
    build: .
    image: matt/react:latest
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./src
        target: /opt/project/src
volumes:
  src: